version: '3'
services: 
    asciidoctor-html:
        image: asciidoctor/docker-asciidoctor
        volumes:
            - .:/documents/
        entrypoint: asciidoctor -D /documents/build pokedex.adoc
    asciidoctor-pdf:
        image: asciidoctor/docker-asciidoctor
        volumes:
            - .:/documents/
        entrypoint: asciidoctor-pdf -D /documents/build pokedex.adoc