Pokedex React Tutorial
======================
Jeroen Nouws <pokedex@moes-media.be>
:doctype: book
:toc:
:toc-title: {doctitle} - T.O.C.
:toclevels: 2
:description: Accompanying tutorial for the Pokedex React Bootcamp
:numbered:
:idprefixed:
:source-highlighter: rouge

Click here if you rather have a link:pokedex.pdf[PDF]

[preface]
== Preface
=== Asumptions
The reader of this tutorial should have a basic understanding of web based technologies such as html, css and javascript.

=== Versions used
* node: 14 (LTS)
* yarn: 1.22.5
* react: 17

=== Code Examples
Reading a tutorial can give you insights into a tech stack, but writing code and testing it gives you a good feeling of learning to work with React. 
All code is available on link:https://github.com/MOES-Media/pokedex-react[Github].

=== Commands and CLI
All commands in this tutorial are run in a bash shell on linux and not tested in windows based terminals like command prompt or Powershell.

= I. Introduction 

include::chapters/typescript-primer.adoc[]

include::chapters/project-setup.adoc[]

= II. Components & Containers
In the next chapters we'll focus on building the UI with React, we'll do so by implementing the component/container pattern. By doing so we'll make a clear seperation of presentational components and logical components. 

NOTE: 'Seperation of Concerns' is a design principle for seperating your code into distinctive sections or concerns. In our case presentational vs logical.

include::chapters/first-component.adoc[]

include::chapters/composed-component.adoc[]

include::chapters/stateless-vs-statefull-components.adoc[]

= III. State management & Middleware

== redux stuff

== Middleware

=== Redux Thunk

=== React router

== What's next?

=== Securing your application

=== Serverless
